# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 08:50
from __future__ import unicode_literals

from django.db import migrations, models
import feed.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=100, verbose_name="Прізвище та ім'я")),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=12, verbose_name='Телефон')),
                ('city', models.CharField(max_length=64, verbose_name='місце проживання')),
                ('bio', models.TextField()),
                ('birth_date', models.DateField(verbose_name='дата народження')),
                ('weight_category', models.CharField(choices=[('lt44', 'менше 44кг'), ('lt48', 'менше 48кг'), ('lt52', 'менше 52кг'), ('lt56', 'менше 56кг'), ('lt60', 'менше 60кг'), ('lt67.5', 'менше 67.5кг'), ('lt75', 'менше 75кг'), ('lt82.5', 'менше 82.5кг'), ('lt90', 'менше 90кг'), ('lt100', 'менше 100кг'), ('gt100f', 'понад 100кг (жінки)'), ('lt110', 'менше 110кг'), ('lt125', 'менше 125кг'), ('lt140', 'менше 140кг'), ('gt140', 'понад 140кг')], max_length=10, verbose_name='вагова категорія')),
                ('age_category', models.CharField(blank=True, editable=False, max_length=25, verbose_name='вікова категорія')),
                ('image', models.ImageField(blank=True, null=True, upload_to=feed.utils.get_upload_location, verbose_name='Фото')),
                ('slug', models.SlugField(blank=True, max_length=100, unique=True, verbose_name='URL')),
                ('status', models.CharField(choices=[('p', 'Учасник'), ('m', 'Член')], max_length=1)),
            ],
            options={
                'verbose_name': 'особові картки',
                'ordering': ('full_name',),
            },
        ),
    ]
