# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'ordering': ('full_name',), 'verbose_name': 'особова картка', 'verbose_name_plural': 'особові картки'},
        ),
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(choices=[('m', 'Чоловіча'), ('f', 'Жіноча')], default='m', max_length=1, verbose_name='стать'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('p', 'Учасник'), ('m', 'Член')], default='m', max_length=1),
        ),
    ]
