# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-04 09:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_auto_20170304_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='age_category',
            field=models.CharField(blank=True, editable=False, max_length=35, verbose_name='вікова категорія'),
        ),
    ]
