# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import feed.utils


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Album',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=64, verbose_name='Назва')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата створення')),
            ],
        ),
        migrations.CreateModel(
            name='Photo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=64, verbose_name='Назва')),
                ('image', models.ImageField(upload_to=feed.utils.get_upload_location, verbose_name='зображення')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата створення')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='gallery.Album')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(db_index=True, max_length=64, verbose_name='Назва')),
                ('url', models.URLField(verbose_name='URL')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='дата створення')),
            ],
        ),
    ]
