# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-09 20:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20170309_2153'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='status',
            field=models.CharField(choices=[('draft', 'Редагується'), ('published', 'Опубліковано')], default='draft', max_length=10, verbose_name='статус'),
        ),
        migrations.AddField(
            model_name='video',
            name='status',
            field=models.CharField(choices=[('draft', 'Редагується'), ('published', 'Опубліковано')], default='draft', max_length=10, verbose_name='статус'),
        ),
    ]
