# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 19:40
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import feed.utils


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='new',
            options={'ordering': ('-publish_date',), 'verbose_name': 'новина', 'verbose_name_plural': 'Новини'},
        ),
        migrations.AlterField(
            model_name='new',
            name='content',
            field=models.TextField(verbose_name='зміст'),
        ),
        migrations.AlterField(
            model_name='new',
            name='created',
            field=models.DateTimeField(auto_now_add=True, verbose_name='створено'),
        ),
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=feed.utils.get_upload_location, verbose_name='зображення'),
        ),
        migrations.AlterField(
            model_name='new',
            name='publish_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата публікації'),
        ),
        migrations.AlterField(
            model_name='new',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True, verbose_name='URL'),
        ),
        migrations.AlterField(
            model_name='new',
            name='status',
            field=models.CharField(choices=[('draft', 'Редагується'), ('published', 'Опубліковано')], default='draft', max_length=10, verbose_name='статус'),
        ),
        migrations.AlterField(
            model_name='new',
            name='title',
            field=models.CharField(db_index=True, max_length=140, unique=True, verbose_name='назва'),
        ),
        migrations.AlterField(
            model_name='new',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='редаговано'),
        ),
        migrations.AlterField(
            model_name='new',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='news', to=settings.AUTH_USER_MODEL, verbose_name='користувач'),
        ),
        migrations.AlterField(
            model_name='new',
            name='views',
            field=models.PositiveIntegerField(default=0, verbose_name='кількість переглядів'),
        ),
    ]
