# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 20:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import feed.utils


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('feed', '0002_auto_20170227_2140'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=feed.utils.get_upload_location, verbose_name='зображення')),
                ('title', models.CharField(db_index=True, max_length=140, unique=True, verbose_name='назва')),
                ('content', models.TextField(verbose_name='зміст')),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True, verbose_name='URL')),
                ('views', models.PositiveIntegerField(default=0, verbose_name='кількість переглядів')),
                ('publish_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='дата публікації')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='створено')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='редаговано')),
                ('status', models.CharField(choices=[('draft', 'Редагується'), ('published', 'Опубліковано')], default='draft', max_length=10, verbose_name='статус')),
            ],
            options={
                'ordering': ('-publish_date',),
                'verbose_name': 'стаття',
                'verbose_name_plural': 'статті',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=25)),
            ],
            options={
                'ordering': ('name',),
                'verbose_name': 'тег',
                'verbose_name_plural': 'теги',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='tags',
            field=models.ManyToManyField(related_name='articles', to='feed.Tag'),
        ),
        migrations.AddField(
            model_name='article',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='articles', to=settings.AUTH_USER_MODEL, verbose_name='користувач'),
        ),
    ]
