# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 20:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed', '0003_auto_20170227_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='slug',
            field=models.SlugField(default='lul', max_length=25, unique=True),
            preserve_default=False,
        ),
    ]
